In [2]:
import pandas as pd

# Load JSON directly into a table (DataFrame)
df = pd.read_json("/home/tichar/Documents/ee798/project/results/cross_encoders.json")
df
cols = [c for c in df.columns if "descriptions" in c]
cols

['BAAI/bge-reranker-base (descriptions)',
 'MoritzLaurer/deberta-v3-large-zeroshot-v2.0 (descriptions)',
 'facebook/bart-large-mnli (descriptions)',
 'cross-encoder/nli-deberta-v3-base (descriptions)',
 'MoritzLaurer/bge-m3-zeroshot-v2.0 (descriptions)',
 'MoritzLaurer/deberta-v3-base-zeroshot-v2.0 (descriptions)']

In [3]:
cols = [c for c in df.columns if "descriptions" not in c]
cols

['BAAI/bge-reranker-base',
 'MoritzLaurer/deberta-v3-large-zeroshot-v2.0',
 'facebook/bart-large-mnli',
 'cross-encoder/nli-deberta-v3-base',
 'MoritzLaurer/bge-m3-zeroshot-v2.0',
 'MoritzLaurer/deberta-v3-base-zeroshot-v2.0',
 'MoritzLaurer/deberta-v3-large-zeroshot-v2.0 (labels)',
 'MoritzLaurer/deberta-v3-base-zeroshot-v2.0 (labels)',
 'facebook/bart-large-mnli (labels)',
 'cross-encoder/nli-deberta-v3-base (labels)',
 'MoritzLaurer/bge-m3-zeroshot-v2.0 (labels)']

In [4]:
accuracy = df[cols].apply(lambda col: col.map( lambda cell: cell.get('accuracy') if isinstance(cell, dict) else None ))
accuracy

,BAAI/bge-reranker-base,MoritzLaurer/deberta-v3-large-zeroshot-v2.0,facebook/bart-large-mnli,cross-encoder/nli-deberta-v3-base,MoritzLaurer/bge-m3-zeroshot-v2.0,MoritzLaurer/deberta-v3-base-zeroshot-v2.0,MoritzLaurer/deberta-v3-large-zeroshot-v2.0 (labels),MoritzLaurer/deberta-v3-base-zeroshot-v2.0 (labels),facebook/bart-large-mnli (labels),cross-encoder/nli-deberta-v3-base (labels),MoritzLaurer/bge-m3-zeroshot-v2.0 (labels)
emotion,0.384500,0.700000,0.493000,0.358000,0.697500,0.748000,NaN,NaN,NaN,NaN,NaN
banking77,0.555592,0.721717,0.508127,0.330949,0.653121,0.711964,0.677828,0.653446,0.467165,0.403771,0.663849
commonsense_qa,0.352989,0.536446,0.406224,0.433251,0.339885,0.438165,NaN,NaN,NaN,NaN,NaN
ag_news,0.644211,0.893289,0.674211,0.669342,0.867632,0.877500,NaN,NaN,NaN,NaN,NaN

In [11]:
import pandas as pd

DIR = "/home/tichar/Documents/ee798/project/results/"
FILES = {
    "Bi-encoders":   DIR + "sentence_encoders.json",
    "Cross-encoders": DIR + "cross_encoders.json",
    "Fine-tune-Cross encoders": DIR + "finetuned_cross_encoders.json",   # add when you have it
    "Fine-tune-Bi encoders": DIR + "finetuned_sentence_encoders.json"        # add when you have it
}

exclude = ["descriptions", "checkpoints","labels"]   # keep only plain base runs
DS_NAMES = {"ag_news": "AG News", "banking77": "Banking77",
            "emotion": "Emotion", "commonsense_qa": "CSQA"}  # adjust to your keys

def load_base(path, metric="accuracy"):
    df = pd.read_json(path)
    print(path.split("/")[-1], "->", df.columns.tolist())   # sanity check
    cols = [c for c in df.columns if not any(e in c for e in exclude)]
    t = df[cols].apply(lambda col: col.map(
        lambda x: x.get(metric) if isinstance(x, dict) else None))
    t = (t.T * 100).astype(float).round(1)
    t.index = [m.split("/")[-1] for m in t.index]
    return t.rename(columns=DS_NAMES)

groups = {g: load_base(p) for g, p in FILES.items()}

sentence_encoders.json -> ['BAAI/bge-m3 (descriptions)', 'BAAI/bge-small-en-v1.5 (descriptions)', 'BAAI/bge-small-en-v1.5', 'BAAI/bge-m3', 'sentence-transformers/all-MiniLM-L6-v2', 'intfloat/e5-small-v2', 'intfloat/e5-small-v2(descriptions)', 'sentence-transformers/all-MiniLM-L6-v2(descriptions)']
cross_encoders.json -> ['BAAI/bge-reranker-base', 'BAAI/bge-reranker-base (descriptions)', 'MoritzLaurer/deberta-v3-large-zeroshot-v2.0', 'MoritzLaurer/deberta-v3-large-zeroshot-v2.0 (descriptions)', 'facebook/bart-large-mnli', 'facebook/bart-large-mnli (descriptions)', 'cross-encoder/nli-deberta-v3-base', 'cross-encoder/nli-deberta-v3-base (descriptions)', 'MoritzLaurer/bge-m3-zeroshot-v2.0', 'MoritzLaurer/bge-m3-zeroshot-v2.0 (descriptions)', 'MoritzLaurer/deberta-v3-base-zeroshot-v2.0', 'MoritzLaurer/deberta-v3-base-zeroshot-v2.0 (descriptions)', 'MoritzLaurer/deberta-v3-large-zeroshot-v2.0 (labels)', 'MoritzLaurer/deberta-v3-base-zeroshot-v2.0 (labels)', 'facebook/bart-large-mnli (labels)', 'cross-encoder/nli-deberta-v3-base (labels)', 'MoritzLaurer/bge-m3-zeroshot-v2.0 (labels)']
finetuned_cross_encoders.json -> ['checkpoints/deberta-v3-base-zeroshot-v2.0-ag_news', 'checkpoints/deberta-v3-base-zeroshot-v2.0-emotion', 'checkpoints/deberta-v3-base-zeroshot-v2.0-banking77', 'checkpoints/deberta-v3-base-zeroshot-v2.0-commonsense_qa', 'checkpoints/nli-deberta-v3-base-ag_news', 'checkpoints/nli-deberta-v3-base-emotion', 'checkpoints/nli-deberta-v3-base-banking77', 'checkpoints/nli-deberta-v3-base-commonsense_qa']
finetuned_sentence_encoders.json -> ['checkpoints/bge-small-ag_news', 'checkpoints/bge-small-emotion', 'checkpoints/bge-small-banking77', 'checkpoints/all-MiniLM-L6-v2-emotion', 'checkpoints/all-MiniLM-L6-v2-banking77', 'checkpoints/all-MiniLM-L6-v2-ag_news', 'checkpoints/e5-small-v2-ag_news', 'checkpoints/e5-small-v2-banking77', 'checkpoints/e5-small-v2-emotion', 'checkpoints/all-MiniLM-L6-v2-commonsense_qa', 'checkpoints/bge-small-commonsense_qa', 'checkpoints/e5-small-v2-commonsense_qa']

In [12]:
DS_NAMES = {"ag_news": "AG News", "emotion": "Emotion",
            "banking77": "Banking77", "commonsense_qa": "CSQA"}   # fixed key

ASSOC  = ["AG News", "Emotion", "Banking77"]
CHANCE = {"AG News": 25.0, "Emotion": 100/6, "Banking77": 100/77, "CSQA": 20.0}

def fancy_latex(groups, caption, label):
    allt = pd.concat(groups.values())[ASSOC + ["CSQA"]].copy()
    allt["Avg"] = allt[ASSOC].mean(axis=1)
    cols = ASSOC + ["Avg", "CSQA"]
    allt = allt[cols]
    best = allt.max()
    second = allt.apply(lambda c: c.dropna().nlargest(2).iloc[-1])

    def cell(v, c):
        if pd.isna(v):
            return "--"
        s = f"{v:.1f}"
        if v == best[c]:
            s = rf"\textbf{{{s}}}"
        elif v == second[c]:
            s = rf"\underline{{{s}}}"
        ch = CHANCE.get(c, sum(CHANCE[a] for a in ASSOC) / 3)
        norm = min(max((v - ch) / (100 - ch), 0), 1)       # chance-normalized
        return rf"\cellcolor{{teal!{int(55 * norm)}}}{s}"

    body = []
    for gi, (g, t) in enumerate(groups.items()):
        if gi > 0:
            body.append(r"\midrule")
        body.append(rf"\multicolumn{{{len(cols)+1}}}{{l}}{{\textit{{{g}}}}} \\")
        for model in t.index:
            row = allt.loc[model]
            name = r"\texttt{" + model.replace("_", r"\_") + "}"
            body.append(rf"\quad {name} & " +
                        " & ".join(cell(row[c], c) for c in cols) + r" \\")

    body.append(r"\midrule")
    chance_cells = [f"{CHANCE[a]:.1f}" for a in ASSOC] + \
                   [f"{sum(CHANCE[a] for a in ASSOC)/3:.1f}", f"{CHANCE['CSQA']:.1f}"]
    body.append(r"\textit{Chance} & " + " & ".join(chance_cells) + r" \\")

    return (
        "\\begin{table*}[t]\n\\centering\\small\n"
        f"\\caption{{{caption}}}\n\\label{{{label}}}\n"
        "\\begin{tabular}{lcccc|c}\n\\toprule\n"
        "& \\multicolumn{4}{c|}{\\textbf{Association tasks}} & \\textbf{Reasoning probe} \\\\\n"
        "\\cmidrule(lr){2-5}\\cmidrule(l){6-6}\n"
        "Model & " + " & ".join(cols) + " \\\\\n\\midrule\n"
        + "\n".join(body) + "\n\\bottomrule\n\\end{tabular}\n\\end{table*}"
    )

print(fancy_latex(groups,
  "Zero-shot accuracy (\\%) with label names only. Shading shows chance-normalized "
  "accuracy; best in bold, second best underlined.", "tab:base"))

\begin{table*}[t]
\centering\small
\caption{Zero-shot accuracy (\%) with label names only. Shading shows chance-normalized accuracy; best in bold, second best underlined.}
\label{tab:base}
\begin{tabular}{lcccc|c}
\toprule
& \multicolumn{4}{c|}{\textbf{Association tasks}} & \textbf{Reasoning probe} \\
\cmidrule(lr){2-5}\cmidrule(l){6-6}
Model & AG News & Emotion & Banking77 & Avg & CSQA \\
\midrule
\multicolumn{6}{l}{\textit{Bi-encoders}} \\
\quad \texttt{bge-small-en-v1.5} & \cellcolor{teal!32}69.3 & \cellcolor{teal!21}49.6 & \cellcolor{teal!37}67.9 & \cellcolor{teal!30}62.3 & \cellcolor{teal!14}40.4 \\
\quad \texttt{bge-m3} & \cellcolor{teal!35}73.1 & \cellcolor{teal!16}41.7 & \cellcolor{teal!35}64.7 & \cellcolor{teal!29}59.8 & \cellcolor{teal!15}42.4 \\
\quad \texttt{all-MiniLM-L6-v2} & \cellcolor{teal!28}64.2 & \cellcolor{teal!17}43.7 & \cellcolor{teal!33}62.3 & \cellcolor{teal!27}56.7 & \cellcolor{teal!13}40.3 \\
\quad \texttt{e5-small-v2} & \cellcolor{teal!31}68.5 & \cellcolor{teal!19}46.4 & \cellcolor{teal!32}58.9 & \cellcolor{teal!27}57.9 & \cellcolor{teal!14}41.1 \\
\midrule
\multicolumn{6}{l}{\textit{Cross-encoders}} \\
\quad \texttt{bge-reranker-base} & \cellcolor{teal!28}64.4 & \cellcolor{teal!14}38.4 & \cellcolor{teal!30}55.6 & \cellcolor{teal!24}52.8 & \cellcolor{teal!10}35.3 \\
\quad \texttt{deberta-v3-large-zeroshot-v2.0} & \cellcolor{teal!47}\textbf{89.3} & \cellcolor{teal!35}\underline{70.0} & \cellcolor{teal!39}\textbf{72.2} & \cellcolor{teal!40}\underline{77.2} & \cellcolor{teal!23}\textbf{53.6} \\
\quad \texttt{bart-large-mnli} & \cellcolor{teal!31}67.4 & \cellcolor{teal!21}49.3 & \cellcolor{teal!27}50.8 & \cellcolor{teal!26}55.8 & \cellcolor{teal!14}40.6 \\
\quad \texttt{nli-deberta-v3-base} & \cellcolor{teal!30}66.9 & \cellcolor{teal!12}35.8 & \cellcolor{teal!17}33.1 & \cellcolor{teal!19}45.3 & \cellcolor{teal!16}43.3 \\
\quad \texttt{bge-m3-zeroshot-v2.0} & \cellcolor{teal!45}86.8 & \cellcolor{teal!35}69.8 & \cellcolor{teal!35}65.3 & \cellcolor{teal!38}74.0 & \cellcolor{teal!9}34.0 \\
\quad \texttt{deberta-v3-base-zeroshot-v2.0} & \cellcolor{teal!46}\underline{87.8} & \cellcolor{teal!38}\textbf{74.8} & \cellcolor{teal!38}\underline{71.2} & \cellcolor{teal!40}\textbf{77.9} & \cellcolor{teal!16}\underline{43.8} \\
\midrule
\multicolumn{6}{l}{\textit{Fine-tune-Cross encoders}} \\
\midrule
\multicolumn{6}{l}{\textit{Fine-tune-Bi encoders}} \\
\midrule
\textit{Chance} & 25.0 & 16.7 & 1.3 & 14.3 & 20.0 \\
\bottomrule
\end{tabular}
\end{table*}

In [13]:
import re

ASSOC = ["AG News", "Emotion", "Banking77"]          # CSQA excluded (choices differ per question)

def load_desc(path, metric="accuracy"):
    df = pd.read_json(path)
    cols = [c for c in df.columns if "descriptions" in c and "checkpoints" not in c]
    t = df[cols].apply(lambda col: col.map(
        lambda x: x.get(metric) if isinstance(x, dict) else None))
    t = (t.T * 100).astype(float).round(1)
    # "BAAI/bge-m3 (descriptions)" -> "bge-m3"
    t.index = [re.sub(r"\s*\(?descriptions?\)?\s*", "", m).split("/")[-1].strip() for m in t.index]
    return t.rename(columns=DS_NAMES)

desc_groups = {g: load_desc(p) for g, p in FILES.items()}

def to_assoc(t):
    t = t.reindex(columns=ASSOC).copy()
    t["Avg"] = t[ASSOC].mean(axis=1)
    return t

# Quick look at the deltas (descriptions minus base), in accuracy points
B = to_assoc(pd.concat(groups.values()))
D = to_assoc(pd.concat(desc_groups.values()))
missing = set(D.index) - set(B.index)
assert not missing, f"names don't match the base table: {missing}"
print((D - B.reindex(D.index)).round(1))

                                AG News  Emotion  Banking77  Avg
bge-m3                              7.7      2.5        4.5  4.9
bge-small-en-v1.5                  11.5     -2.9        2.5  3.7
e5-small-v2                        11.4     -0.2        6.1  5.8
all-MiniLM-L6-v2                   13.3      1.4        4.3  6.3
bge-reranker-base                   7.1      8.3        5.1  6.8
deberta-v3-large-zeroshot-v2.0     -0.2     -1.3       -4.8 -2.1
bart-large-mnli                    11.5      5.9       -6.8  3.5
nli-deberta-v3-base                -6.3      5.4        6.7  1.9
bge-m3-zeroshot-v2.0                2.0     -1.4       -5.7 -1.7
deberta-v3-base-zeroshot-v2.0       1.8     -6.2       -7.7 -4.0

In [14]:
def desc_latex(desc_groups, base_groups, caption, label):
    cols = ASSOC + ["Avg"]
    D = to_assoc(pd.concat(desc_groups.values()))
    B = to_assoc(pd.concat(base_groups.values()))
    best = D.max()

    def cell(v, d, c):
        if pd.isna(v):
            return "--"
        s = f"{v:.1f}"
        if v == best[c]:
            s = rf"\textbf{{{s}}}"
        if pd.isna(d):
            return s
        shade = min(int(4 * abs(d)), 50)                    # 12.5 points or more saturates
        colour = "green" if d >= 0 else "red"
        return rf"\cellcolor{{{colour}!{shade}}}{s}\,{{\scriptsize({d:+.1f})}}"

    body = []
    for gi, (g, t) in enumerate(desc_groups.items()):
        if gi > 0:
            body.append(r"\midrule")
        body.append(rf"\multicolumn{{{len(cols)+1}}}{{l}}{{\textit{{{g}}}}} \\")
        for model in t.index:
            name = r"\texttt{" + model.replace("_", r"\_") + "}"
            cells = []
            for c in cols:
                base_v = B.loc[model, c] if model in B.index else float("nan")
                cells.append(cell(D.loc[model, c], D.loc[model, c] - base_v, c))
            body.append(rf"\quad {name} & " + " & ".join(cells) + r" \\")

    return (
        "\\begin{table*}[t]\n\\centering\\small\n"
        f"\\caption{{{caption}}}\n\\label{{{label}}}\n"
        "\\begin{tabular}{lccc|c}\n\\toprule\n"
        "Model & " + " & ".join(cols) + " \\\\\n\\midrule\n"
        + "\n".join(body) + "\n\\bottomrule\n\\end{tabular}\n\\end{table*}"
    )

print(desc_latex(desc_groups, groups,
  "Zero-shot accuracy (\\%) with class descriptions. Bracketed values are the change "
  "from label names only (Table~\\ref{tab:base}); green marks gains, red marks losses. "
  "Best in bold. Avg is the raw mean over the three tasks.",
  "tab:desc"))

\begin{table*}[t]
\centering\small
\caption{Zero-shot accuracy (\%) with class descriptions. Bracketed values are the change from label names only (Table~\ref{tab:base}); green marks gains, red marks losses. Best in bold. Avg is the raw mean over the three tasks.}
\label{tab:desc}
\begin{tabular}{lccc|c}
\toprule
Model & AG News & Emotion & Banking77 & Avg \\
\midrule
\multicolumn{5}{l}{\textit{Bi-encoders}} \\
\quad \texttt{bge-m3} & \cellcolor{green!30}80.8\,{\scriptsize(+7.7)} & \cellcolor{green!10}44.2\,{\scriptsize(+2.5)} & \cellcolor{green!18}69.2\,{\scriptsize(+4.5)} & \cellcolor{green!19}64.7\,{\scriptsize(+4.9)} \\
\quad \texttt{bge-small-en-v1.5} & \cellcolor{green!46}80.8\,{\scriptsize(+11.5)} & \cellcolor{red!11}46.7\,{\scriptsize(-2.9)} & \cellcolor{green!10}\textbf{70.4}\,{\scriptsize(+2.5)} & \cellcolor{green!14}66.0\,{\scriptsize(+3.7)} \\
\quad \texttt{e5-small-v2} & \cellcolor{green!45}79.9\,{\scriptsize(+11.4)} & \cellcolor{red!0}46.2\,{\scriptsize(-0.2)} & \cellcolor{green!24}65.0\,{\scriptsize(+6.1)} & \cellcolor{green!23}63.7\,{\scriptsize(+5.8)} \\
\quad \texttt{all-MiniLM-L6-v2} & \cellcolor{green!50}77.5\,{\scriptsize(+13.3)} & \cellcolor{green!5}45.1\,{\scriptsize(+1.4)} & \cellcolor{green!17}66.6\,{\scriptsize(+4.3)} & \cellcolor{green!25}63.1\,{\scriptsize(+6.3)} \\
\midrule
\multicolumn{5}{l}{\textit{Cross-encoders}} \\
\quad \texttt{bge-reranker-base} & \cellcolor{green!28}71.5\,{\scriptsize(+7.1)} & \cellcolor{green!33}46.7\,{\scriptsize(+8.3)} & \cellcolor{green!20}60.7\,{\scriptsize(+5.1)} & \cellcolor{green!27}59.6\,{\scriptsize(+6.8)} \\
\quad \texttt{deberta-v3-large-zeroshot-v2.0} & \cellcolor{red!0}89.1\,{\scriptsize(-0.2)} & \cellcolor{red!5}\textbf{68.7}\,{\scriptsize(-1.3)} & \cellcolor{red!19}67.4\,{\scriptsize(-4.8)} & \cellcolor{red!8}\textbf{75.1}\,{\scriptsize(-2.1)} \\
\quad \texttt{bart-large-mnli} & \cellcolor{green!46}78.9\,{\scriptsize(+11.5)} & \cellcolor{green!23}55.2\,{\scriptsize(+5.9)} & \cellcolor{red!27}44.0\,{\scriptsize(-6.8)} & \cellcolor{green!14}59.4\,{\scriptsize(+3.5)} \\
\quad \texttt{nli-deberta-v3-base} & \cellcolor{red!25}60.6\,{\scriptsize(-6.3)} & \cellcolor{green!21}41.2\,{\scriptsize(+5.4)} & \cellcolor{green!26}39.8\,{\scriptsize(+6.7)} & \cellcolor{green!7}47.2\,{\scriptsize(+1.9)} \\
\quad \texttt{bge-m3-zeroshot-v2.0} & \cellcolor{green!8}88.8\,{\scriptsize(+2.0)} & \cellcolor{red!5}68.4\,{\scriptsize(-1.4)} & \cellcolor{red!22}59.6\,{\scriptsize(-5.7)} & \cellcolor{red!6}72.3\,{\scriptsize(-1.7)} \\
\quad \texttt{deberta-v3-base-zeroshot-v2.0} & \cellcolor{green!7}\textbf{89.6}\,{\scriptsize(+1.8)} & \cellcolor{red!24}68.6\,{\scriptsize(-6.2)} & \cellcolor{red!30}63.5\,{\scriptsize(-7.7)} & \cellcolor{red!16}73.9\,{\scriptsize(-4.0)} \\
\midrule
\multicolumn{5}{l}{\textit{Fine-tune-Cross encoders}} \\
\midrule
\multicolumn{5}{l}{\textit{Fine-tune-Bi encoders}} \\
\bottomrule
\end{tabular}
\end{table*}

In [15]:
import re

def load_ft(path, metric="accuracy"):
    df = pd.read_json(path)
    rows = []
    for col in [c for c in df.columns if "checkpoint" in c]:
        for ds, cell in df[col].items():
            if isinstance(cell, dict):
                short = col.split("/")[-1]
                model = re.sub(rf"[-_]{re.escape(ds)}$", "", short)      # "bge-small-ag_news" -> "bge-small"
                rows.append({"ckpt": col, "model": model,
                             "dataset": DS_NAMES.get(ds, ds), "acc": cell[metric] * 100})
    return pd.DataFrame(rows)

ft = pd.concat([load_ft(p).assign(group=g) for g, p in FILES.items()], ignore_index=True)

# match checkpoint model names to base-table names by prefix
base_all = pd.concat(groups.values())
def match_base(m):
    idx = list(base_all.index)
    exact = [b for b in idx if b.lower() == m.lower()]
    if exact:
        return exact[0]
    hits = [b for b in idx if b.lower().startswith(m.lower())]
    if len(hits) == 1:
        return hits[0]
    if len(hits) > 1:
        print(f"ambiguous: {m} -> {hits}")
    return None
ft["base_model"] = ft["model"].map(match_base)
print("unmatched:", ft[ft.base_model.isna()].ckpt.unique())             # fix these by hand if any
ft = ft.dropna(subset=["base_model"])

FT_COLS = ["AG News", "Emotion", "Banking77", "CSQA"]
acc = ft.pivot_table(index="base_model", columns="dataset", values="acc").reindex(columns=FT_COLS)
base = base_all.reindex(index=acc.index, columns=FT_COLS)
delta = acc - base
print(delta.round(1))

unmatched: <ArrowStringArray>
[]
Length: 0, dtype: str
dataset                        AG News  Emotion  Banking77  CSQA
base_model
all-MiniLM-L6-v2                  24.3     17.1        6.1  -0.3
bge-small-en-v1.5                 21.7     15.5        6.4   0.8
deberta-v3-base-zeroshot-v2.0      4.0      8.8        5.8  12.6
e5-small-v2                       22.9     21.2        9.4   6.0
nli-deberta-v3-base               24.2     32.6       32.6   9.9

In [16]:
import json
import re
from pathlib import Path

FT_FILES = {
    "Fine-tuned cross-encoders": FILES["Fine-tune-Cross encoders"],
    "Fine-tuned bi-encoders": FILES["Fine-tune-Bi encoders"],
}

DS_NAMES = {
    "ag_news": "AG News",
    "emotion": "Emotion",
    "banking77": "Banking77",
    "commonsense_qa": "CSQA",
}

DATASET_SUFFIXES = {
    "ag_news": ("ag_news", "ag-news", "agnews"),
    "emotion": ("emotion",),
    "banking77": ("banking77",),
    "commonsense_qa": ("commonsense_qa", "commonsense-qa", "commonsenseqa"),
}

def strip_dataset_suffix(checkpoint_name, dataset):
    for suffix in sorted(DATASET_SUFFIXES.get(dataset, (dataset,)), key=len, reverse=True):
        model = re.sub(rf"[-_]{re.escape(suffix)}$", "", checkpoint_name, flags=re.IGNORECASE)
        if model != checkpoint_name:
            return model
    return checkpoint_name

def load_ft(path, group, metric="accuracy"):
    with open(path, encoding="utf-8") as f:
        results = json.load(f)

    rows = []
    for checkpoint, dataset_results in results.items():
        if not isinstance(dataset_results, dict):
            continue

        checkpoint_name = Path(checkpoint).name

        for dataset, metrics in dataset_results.items():
            if not isinstance(metrics, dict) or metric not in metrics:
                continue

            model = strip_dataset_suffix(checkpoint_name, dataset)
            rows.append({
                "group": group,
                "model": model,
                "checkpoint": checkpoint,
                "dataset": DS_NAMES.get(dataset, dataset),
                "accuracy": metrics[metric] * 100,
            })

    return pd.DataFrame(rows)

ft_long = pd.concat(
    [load_ft(path, group) for group, path in FT_FILES.items()],
    ignore_index=True,
)

# One row per checkpoint naming variant; accuracy is shown as a percentage.
ft_accuracy = (
    ft_long.pivot_table(
        index=["group", "model"],
        columns="dataset",
        values="accuracy",
        aggfunc="first",
    )
    .reindex(columns=["AG News", "Emotion", "Banking77", "CSQA"])
    .round(1)
)

ft_accuracy

dataset                                                  AG News  Emotion  \
group                     model
Fine-tuned bi-encoders    all-MiniLM-L6-v2                  88.5     60.8
                          bge-small                         91.0     65.1
                          e5-small-v2                       91.4     67.6
Fine-tuned cross-encoders deberta-v3-base-zeroshot-v2.0     91.8     83.6
                          nli-deberta-v3-base               91.1     68.4

dataset                                                  Banking77  CSQA
group                     model
Fine-tuned bi-encoders    all-MiniLM-L6-v2                    68.4  40.0
                          bge-small                           74.3  41.2
                          e5-small-v2                         68.3  47.1
Fine-tuned cross-encoders deberta-v3-base-zeroshot-v2.0       77.0  56.4
                          nli-deberta-v3-base                 65.7  53.2

In [17]:
import pandas as pd

FT_COLS = ["AG News", "Emotion", "Banking77", "CSQA"]
ASSOC = ["AG News", "Emotion", "Banking77"]
FT_TABLE_COLS = ASSOC + ["Avg", "CSQA"]
CHANCE = {
    "AG News": 25.0,
    "Emotion": 100 / 6,
    "Banking77": 100 / 77,
    "CSQA": 20.0,
    "Avg": sum([25.0, 100 / 6, 100 / 77]) / 3,
}

# Compare against the corresponding zero-shot bi- or cross-encoder.
base_all = pd.concat([groups["Bi-encoders"], groups["Cross-encoders"]])
base_all = base_all.reindex(columns=FT_COLS)

def match_base_model(model):
    names = list(base_all.index)
    exact = [name for name in names if name.lower() == model.lower()]
    if exact:
        return exact[0]
    matches = [name for name in names if name.lower().startswith(model.lower())]
    if len(matches) == 1:
        return matches[0]
    print(f"Could not uniquely match fine-tuned model {model!r} to a base model: {matches}")
    return None

ft_table = ft_accuracy.copy()
ft_table["base_model"] = [match_base_model(model) for _, model in ft_table.index]
ft_table["Avg"] = ft_table[ASSOC].mean(axis=1)
base_for_ft = base_all.reindex(ft_table["base_model"].to_list())
base_for_ft.index = ft_table.index
base_for_ft["Avg"] = base_for_ft[ASSOC].mean(axis=1)
ft_delta = ft_table[FT_TABLE_COLS] - base_for_ft[FT_TABLE_COLS]


def fine_tuned_latex(table, delta, caption, label):
    best = table.max(axis=0)
    body = []
    groups_in_table = table.index.get_level_values("group").unique()

    def format_cell(value, difference, column):
        if pd.isna(value):
            return "--"

        text = f"{value:.1f}"
        if value == best[column]:
            text = rf"\textbf{{{text}}}"

        if pd.notna(difference):
            text += rf"\,{{\scriptsize({difference:+.1f})}}"

        chance = CHANCE[column]
        normalized = min(max((value - chance) / (100 - chance), 0), 1)
        return rf"\cellcolor{{teal!{int(55 * normalized)}}}{text}"

    for group_index, group in enumerate(groups_in_table):
        if group_index:
            body.append(r"\midrule")

        body.append(rf"\multicolumn{{{len(FT_TABLE_COLS) + 1}}}{{l}}{{\textit{{{group}}}}} \\")
        group_table = table.xs(group, level="group")
        group_delta = delta.xs(group, level="group")
        for model, row in group_table.iterrows():
            model_name = str(model).replace("_", r"\_")
            cells = " & ".join(
                format_cell(row[column], group_delta.loc[model, column], column)
                for column in FT_TABLE_COLS
            )
            body.append(rf"\quad \texttt{{{model_name}}} & {cells} \\")

    chance_cells = " & ".join(f"{CHANCE[column]:.1f}" for column in FT_TABLE_COLS)
    body.extend([
        r"\midrule",
        rf"\textit{{Chance}} & {chance_cells} \\",
    ])

    return (
        "\\begin{table*}[t]\n\\centering\\small\n"
        f"\\caption{{{caption}}}\n\\label{{{label}}}\n"
        "\\begin{tabular}{lcccc|c}\n\\toprule\n"
        "Model & " + " & ".join(FT_TABLE_COLS) + " \\\\\n\\midrule\n"
        + "\n".join(body)
        + "\n\\bottomrule\n\\end{tabular}\n\\end{table*}"
    )

print(fine_tuned_latex(
    ft_table,
    ft_delta,
    "Fine-tuned model accuracy (\\%). Parentheses show the accuracy-point change from the corresponding zero-shot model; Avg is over AG News, Emotion, and Banking77.",
    "tab:finetuned",
))

\begin{table*}[t]
\centering\small
\caption{Fine-tuned model accuracy (\%). Parentheses show the accuracy-point change from the corresponding zero-shot model; Avg is over AG News, Emotion, and Banking77.}
\label{tab:finetuned}
\begin{tabular}{lcccc|c}
\toprule
Model & AG News & Emotion & Banking77 & Avg & CSQA \\
\midrule
\multicolumn{6}{l}{\textit{Fine-tuned bi-encoders}} \\
\quad \texttt{all-MiniLM-L6-v2} & \cellcolor{teal!46}88.5\,{\scriptsize(+24.3)} & \cellcolor{teal!29}60.8\,{\scriptsize(+17.1)} & \cellcolor{teal!37}68.4\,{\scriptsize(+6.1)} & \cellcolor{teal!37}72.6\,{\scriptsize(+15.8)} & \cellcolor{teal!13}40.0\,{\scriptsize(-0.3)} \\
\quad \texttt{bge-small} & \cellcolor{teal!48}91.0\,{\scriptsize(+21.7)} & \cellcolor{teal!31}65.1\,{\scriptsize(+15.5)} & \cellcolor{teal!40}74.3\,{\scriptsize(+6.4)} & \cellcolor{teal!40}76.8\,{\scriptsize(+14.5)} & \cellcolor{teal!14}41.2\,{\scriptsize(+0.8)} \\
\quad \texttt{e5-small-v2} & \cellcolor{teal!48}91.4\,{\scriptsize(+22.9)} & \cellcolor{teal!33}67.6\,{\scriptsize(+21.2)} & \cellcolor{teal!37}68.3\,{\scriptsize(+9.4)} & \cellcolor{teal!39}75.8\,{\scriptsize(+17.8)} & \cellcolor{teal!18}47.1\,{\scriptsize(+6.0)} \\
\midrule
\multicolumn{6}{l}{\textit{Fine-tuned cross-encoders}} \\
\quad \texttt{deberta-v3-base-zeroshot-v2.0} & \cellcolor{teal!48}\textbf{91.8}\,{\scriptsize(+4.0)} & \cellcolor{teal!44}\textbf{83.6}\,{\scriptsize(+8.8)} & \cellcolor{teal!42}\textbf{77.0}\,{\scriptsize(+5.8)} & \cellcolor{teal!44}\textbf{84.1}\,{\scriptsize(+6.2)} & \cellcolor{teal!25}\textbf{56.4}\,{\scriptsize(+12.6)} \\
\quad \texttt{nli-deberta-v3-base} & \cellcolor{teal!48}91.1\,{\scriptsize(+24.2)} & \cellcolor{teal!34}68.4\,{\scriptsize(+32.6)} & \cellcolor{teal!35}65.7\,{\scriptsize(+32.6)} & \cellcolor{teal!38}75.1\,{\scriptsize(+29.8)} & \cellcolor{teal!22}53.2\,{\scriptsize(+9.9)} \\
\midrule
\textit{Chance} & 25.0 & 16.7 & 1.3 & 14.3 & 20.0 \\
\bottomrule
\end{tabular}
\end{table*}

In [7]:
import json
from pathlib import Path

RESULTS = Path("/home/tichar/Documents/ee798/project/results/reasoning_csqa.json")
OUT = Path("/home/tichar/Documents/ee798/project/results/reasoning_table.tex")

DISPLAY = {
    "sentence-transformers/all-MiniLM-L6-v2": "all-MiniLM-L6-v2",
    "intfloat/e5-small-v2": "e5-small-v2",
    "BAAI/bge-small-en-v1.5": "bge-small-en-v1.5",
    "BAAI/bge-m3": "bge-m3",
    "MoritzLaurer/deberta-v3-large-zeroshot-v2.0": "DeBERTa-L-ZS",
    "MoritzLaurer/deberta-v3-base-zeroshot-v2.0": "DeBERTa-B-ZS",
    "facebook/bart-large-mnli": "BART-large-MNLI",
    "cross-encoder/nli-deberta-v3-base": "NLI-DeBERTa-B",
    "MoritzLaurer/bge-m3-zeroshot-v2.0": "bge-m3-ZS",
    "BAAI/bge-reranker-base": "bge-reranker-base",
}
GROUPS = [("Bi-encoders", "sentence_encoder"),
          ("Cross-encoders", "nli"),
          ("Reranker", "reranker")]
CHANCE = 20.0
SHADE_SCALE, SHADE_CAP = 3, 45
NCOLS = 8


def esc(s):
    return s.replace("_", r"\_")


def signed(x, nd=1):
    return f"{x:+.{nd}f}".replace("-", "$-$")


def shade(delta):
    if delta is None or abs(delta) < 0.05:
        return ""
    color = "teal" if delta > 0 else "red"
    return rf"\cellcolor{{{color}!{min(SHADE_CAP, int(round(abs(delta) * SHADE_SCALE)))}}}"


def delta_cell(d, sig=False):
    if d is None:
        return "--"
    return f"{shade(d)}{signed(d)}" + (r"$^{\dagger}$" if sig else "")


def acc_cell(v, best):
    s = f"{v:.1f}"
    return rf"\textbf{{{s}}}" if abs(v - best) < 1e-9 else s


data = json.loads(RESULTS.read_text())
data.pop("metadata", None)

rows = {}
for name, m in data.items():
    if "error" in m:
        print(f"skipping {name}: {m['error']}")
        continue
    c, cmp_ = m["conditions"], m["comparisons"]["nonleak"]
    base, rat, shuf = (c[k]["acc"] * 100 for k in ("base", "rat", "shuf"))
    nb, nr = c["base"]["acc_nonleak"], c["rat"]["acc_nonleak"]
    p = cmp_["rat_vs_base_p"]
    rows[name] = dict(
        type=m["model_type"], base=base, rat=rat, shuf=shuf,
        d_all=rat - base,
        d_f=(nr - nb) * 100 if nb is not None and nr is not None else None,
        sig=(p is not None and p < 0.05),
        mb=c["base"]["norm_margin_mean"], mr=c["rat"]["norm_margin_mean"],
    )

best_base = max(r["base"] for r in rows.values())
best_rat = max(r["rat"] for r in rows.values())

L = []
add = L.append
add(r"\begin{table}[t]")
add(r"\centering\footnotesize")
add(r"\setlength{\tabcolsep}{3pt}")
add(r"\caption{Rationale-assisted CSQA accuracy (\%). Base: question only; Rat: question plus an "
    r"LLM-generated rationale; Shuf: question plus the rationale of a different question (control). "
    r"$\Delta$: accuracy change of Rat over Base in points, on all items and on the filtered subset "
    r"of items whose rationale does not mention the correct option (teal: gain, red: loss). "
    r"Norm.\ margin: mean of $(s_{\mathrm{correct}}-\max s_{\mathrm{wrong}})/\mathrm{std}(s)$. "
    r"$\dagger$: Rat vs.\ Base significant on the filtered subset (exact McNemar, $p<0.05$). "
    r"Best accuracy per column in bold.}")
add(r"\label{tab:rationale}")
add(r"\begin{tabularx}{\columnwidth}{@{}>{\raggedright\arraybackslash}X" + "c" * (NCOLS - 1) + r"@{}}")
add(r"\toprule")
add(r"& \multicolumn{3}{c}{Accuracy} & \multicolumn{2}{c}{$\Delta$ Rat$-$Base} "
    r"& \multicolumn{2}{c}{Norm.\ margin} \\")
add(r"\cmidrule(lr){2-4}\cmidrule(lr){5-6}\cmidrule(l){7-8}")
add(r"Model & Base & Rat & Shuf & All & Filtered & Base & Rat \\")
add(r"\midrule")

for title, mtype in GROUPS:
    grp = [(n, r) for n, r in rows.items() if r["type"] == mtype]
    if not grp:
        continue
    add(rf"\multicolumn{{{NCOLS}}}{{l}}{{\textit{{{title}}}}} \\")
    for n, r in grp:
        add(rf"\quad \texttt{{{esc(DISPLAY.get(n, n.split('/')[-1]))}}} & "
            rf"{acc_cell(r['base'], best_base)} & {acc_cell(r['rat'], best_rat)} & {r['shuf']:.1f} & "
            rf"{delta_cell(r['d_all'])} & {delta_cell(r['d_f'], r['sig'])} & "
            rf"{signed(r['mb'], 2)} & {signed(r['mr'], 2)} \\")
    add(r"\midrule")

add(rf"\textit{{Chance}} & {CHANCE:.1f} & {CHANCE:.1f} & {CHANCE:.1f} & -- & -- & -- & -- \\")
add(r"\bottomrule")
add(r"\end{tabularx}")
add(r"\end{table}")

tex = "\n".join(L)
OUT.write_text(tex)
print(tex)
print(f"\nsaved {OUT}")

\begin{table}[t]
\centering\footnotesize
\setlength{\tabcolsep}{3pt}
\caption{Rationale-assisted CSQA accuracy (\%). Base: question only; Rat: question plus an LLM-generated rationale; Shuf: question plus the rationale of a different question (control). $\Delta$: accuracy change of Rat over Base in points, on all items and on the filtered subset of items whose rationale does not mention the correct option (teal: gain, red: loss). Norm.\ margin: mean of $(s_{\mathrm{correct}}-\max s_{\mathrm{wrong}})/\mathrm{std}(s)$. $\dagger$: Rat vs.\ Base significant on the filtered subset (exact McNemar, $p<0.05$). Best accuracy per column in bold.}
\label{tab:rationale}
\begin{tabularx}{\columnwidth}{@{}>{\raggedright\arraybackslash}Xccccccc@{}}
\toprule
& \multicolumn{3}{c}{Accuracy} & \multicolumn{2}{c}{$\Delta$ Rat$-$Base} & \multicolumn{2}{c}{Norm.\ margin} \\
\cmidrule(lr){2-4}\cmidrule(lr){5-6}\cmidrule(l){7-8}
Model & Base & Rat & Shuf & All & Filtered & Base & Rat \\
\midrule
\multicolumn{8}{l}{\textit{Bi-encoders}} \\
\quad \texttt{all-MiniLM-L6-v2} & 40.3 & 49.3 & 30.7 & \cellcolor{teal!27}+9.0 & \cellcolor{teal!24}+7.9$^{\dagger}$ & $-$0.47 & $-$0.20 \\
\quad \texttt{e5-small-v2} & 38.7 & 49.0 & 31.3 & \cellcolor{teal!31}+10.3 & \cellcolor{teal!28}+9.4$^{\dagger}$ & $-$0.48 & $-$0.12 \\
\quad \texttt{bge-small-en-v1.5} & 38.3 & 46.3 & 25.0 & \cellcolor{teal!24}+8.0 & \cellcolor{teal!21}+6.9$^{\dagger}$ & $-$0.46 & $-$0.21 \\
\quad \texttt{bge-m3} & 44.3 & 49.3 & 32.3 & \cellcolor{teal!15}+5.0 & \cellcolor{teal!11}+3.6 & $-$0.38 & $-$0.22 \\
\midrule
\multicolumn{8}{l}{\textit{Cross-encoders}} \\
\quad \texttt{DeBERTa-L-ZS} & \textbf{52.3} & \textbf{55.3} & 36.7 & \cellcolor{teal!9}+3.0 & \cellcolor{teal!4}+1.4 & $-$0.12 & +0.14 \\
\quad \texttt{DeBERTa-B-ZS} & 45.3 & 53.3 & 36.3 & \cellcolor{teal!24}+8.0 & \cellcolor{teal!18}+6.1 & $-$0.37 & $-$0.04 \\
\quad \texttt{BART-large-MNLI} & 38.3 & 42.0 & 35.7 & \cellcolor{teal!11}+3.7 & \cellcolor{teal!4}+1.4 & $-$0.54 & $-$0.45 \\
\quad \texttt{NLI-DeBERTa-B} & 42.7 & 48.3 & 34.7 & \cellcolor{teal!17}+5.7 & \cellcolor{teal!11}+3.6 & $-$0.47 & $-$0.23 \\
\quad \texttt{bge-m3-ZS} & 33.3 & 40.3 & 29.7 & \cellcolor{teal!21}+7.0 & \cellcolor{teal!16}+5.4 & $-$0.60 & $-$0.43 \\
\midrule
\multicolumn{8}{l}{\textit{Reranker}} \\
\quad \texttt{bge-reranker-base} & 33.3 & 38.7 & 25.3 & \cellcolor{teal!16}+5.3 & \cellcolor{teal!11}+3.6 & $-$0.67 & $-$0.50 \\
\midrule
\textit{Chance} & 20.0 & 20.0 & 20.0 & -- & -- & -- & -- \\
\bottomrule
\end{tabularx}
\end{table}

saved /home/tichar/Documents/ee798/project/results/reasoning_table.tex

In [8]:
import json
import random
from pathlib import Path

from datasets import load_dataset
from src.configs import DATASETS
from src.dataset_adapters import DATASET_ADAPTERS

SEED = 0
OUT = Path("results/dataset_examples.tex")
DATA_CACHE = "/home/tichar/Documents/ee798/project/data"
DISPLAY = {"ag_news": "AG News", "banking77": "Banking77",
           "emotion": "Emotion", "commonsense_qa": "CSQA"}
ORDER = ["ag_news", "banking77", "emotion", "commonsense_qa"]   # edit to match your config keys
MAX_CHARS = 140                                                  # truncate long inputs in the table


def esc(s):
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                 ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    return s


def clip(s):
    s = " ".join(s.split())
    return s if len(s) <= MAX_CHARS else s[:MAX_CHARS].rsplit(" ", 1)[0] + "..."


rng = random.Random(SEED)
rows = []

for key in ORDER:
    if key not in DATASETS or key not in DATASET_ADAPTERS:
        print(f"skipping {key}: not in DATASETS / DATASET_ADAPTERS (keys: {list(DATASETS)})")
        continue
    config = DATASETS[key]
    dataset = load_dataset(config["hf_name"], cache_dir=DATA_CACHE)
    queries, candidates, labels = DATASET_ADAPTERS[key](dataset, config)

    i = rng.randrange(len(queries))
    opts = candidates[0] if config["shared_candidates"] else candidates[i]
    gold = opts[labels[i]]

    print(f"\n=== {DISPLAY.get(key, key)} | item {i} of {len(queries)} ===")
    print("input :", queries[i])
    print("gold  :", gold)
    print("K     :", len(opts), "| options:", opts if len(opts) <= 10 else opts[:10] + ["..."])

    if config["shared_candidates"]:
        text = esc(clip(queries[i]))
    else:  # per-item options (CSQA): show them with the correct one in bold
        shown = ", ".join(rf"\textbf{{{esc(o)}}}" if j == labels[i] else esc(o)
                          for j, o in enumerate(opts))
        text = f"{esc(clip(queries[i]))} Options: {shown}"
    rows.append((DISPLAY.get(key, key), text, esc(gold)))

L = [r"\begin{table}[htbp]", r"\centering", r"\footnotesize",
     r"\caption{Example inputs and correct labels, one random item per dataset "
     r"(CSQA: correct option in bold).}",
     r"\label{tab:examples}",
     r"\begin{tabularx}{\columnwidth}{@{}l>{\raggedright\arraybackslash}X>{\raggedright\arraybackslash}p{2.1cm}@{}}",
     r"\toprule", r"Dataset & Input & Label \\", r"\midrule"]
for name, text, gold in rows:
    L.append(rf"{name} & ``{text}'' & {gold} \\" if name != "CSQA"
             else rf"{name} & ``{text.split(' Options: ')[0]}'' Options: {text.split(' Options: ')[1]} & {gold} \\")
L += [r"\bottomrule", r"\end{tabularx}", r"\end{table}"]

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(L))
print("\n" + "\n".join(L))
print(f"\nsaved {OUT}")

/home/tichar/Documents/ee798/project/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

=== AG News | item 6917 of 7600 ===
input : Allianz to fight US court ruling on WTC attacks MUNICH - German insurance concern Allianz said on Tuesday it would fight a US jury decision in New York which doubled the amount of insurance which the leaseholder of the destroyed World Trade Center towers could collect from nine insurance firms.
gold  : Business
K     : 4 | options: ['World', 'Sports', 'Business', 'Sci/Tech']

=== Banking77 | item 1577 of 3076 ===
input : My ATM transaction was unsuccessful.
gold  : declined cash withdrawal
K     : 77 | options: ['activate my card', 'age limit', 'apple pay or google pay', 'atm support', 'automatic top up', 'balance not updated after bank transfer', 'balance not updated after cheque or cash deposit', 'beneficiary not allowed', 'cancel transfer', 'card about to expire', '...']

=== Emotion | item 1552 of 2000 ===
input : i am finally starting to feel like i have a real life here in san vicente and i am no longer on a strange confusing extended vacation
gold  : fear
K     : 6 | options: ['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

=== CSQA | item 861 of 1221 ===
input : She asked her little boy why, he replied that he didn't know and it was just what?
gold  : because
K     : 5 | options: ['case', 'reason', 'how', 'because', 'answer']

\begin{table}[htbp]
\centering
\footnotesize
\caption{Example inputs and correct labels, one random item per dataset (CSQA: correct option in bold).}
\label{tab:examples}
\begin{tabularx}{\columnwidth}{@{}l>{\raggedright\arraybackslash}X>{\raggedright\arraybackslash}p{2.1cm}@{}}
\toprule
Dataset & Input & Label \\
\midrule
AG News & ``Allianz to fight US court ruling on WTC attacks MUNICH - German insurance concern Allianz said on Tuesday it would fight a US jury decision...'' & Business \\
Banking77 & ``My ATM transaction was unsuccessful.'' & declined cash withdrawal \\
Emotion & ``i am finally starting to feel like i have a real life here in san vicente and i am no longer on a strange confusing extended vacation'' & fear \\
CSQA & ``She asked her little boy why, he replied that he didn't know and it was just what?'' Options: case, reason, how, \textbf{because}, answer & because \\
\bottomrule
\end{tabularx}
\end{table}

saved results/dataset_examples.tex

In [9]:
import re
import random
import numpy as np
import torch
import torch.nn.functional as F
from pathlib import Path
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification
from src.configs import DATASETS
from src.dataset_adapters import DATASET_ADAPTERS

SEED = 0
DATA_CACHE = "/home/tichar/Documents/ee798/project/data"
OUT = Path("results/qual_examples_todo.tex")
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
EMO_KEY, CSQA_KEY = "emotion", "commonsense_qa"       # edit to match your DATASETS keys
EMO_TEMPLATE = "This example is {}."                   # use the template you actually used for Emotion
CSQA_TEMPLATE = "The answer to the question is {}."
MARGIN_MIN, MAX_Q_CHARS, POOL = 0.8, 100, 300          # POOL: max candidates scored per dataset

# ---------- scorers (fp32, same as the main experiments) ----------
e5_tok = AutoTokenizer.from_pretrained("intfloat/e5-small-v2")
e5 = AutoModel.from_pretrained("intfloat/e5-small-v2").to(DEVICE).eval()

def e5_enc(texts):
    b = e5_tok(["query: " + t for t in texts], padding=True, truncation=True,
               max_length=512, return_tensors="pt").to(DEVICE)
    with torch.inference_mode():
        h = e5(**b).last_hidden_state
    m = b["attention_mask"].unsqueeze(-1).float()
    return F.normalize((h * m).sum(1) / m.sum(1), dim=-1)

def e5_scores(q, opts):
    return (e5_enc([q]) @ e5_enc(opts).T)[0].cpu().numpy()

NLI = "MoritzLaurer/deberta-v3-base-zeroshot-v2.0"
ce_tok = AutoTokenizer.from_pretrained(NLI)
ce = AutoModelForSequenceClassification.from_pretrained(NLI).to(DEVICE).eval()
ENT = next(int(i) for i, l in ce.config.id2label.items() if str(l).lower() == "entailment")

def ce_scores(q, opts, template):
    hyps = [template.format(o) for o in opts]
    b = ce_tok([q] * len(opts), hyps, padding=True, truncation=True,
               max_length=512, return_tensors="pt").to(DEVICE)
    with torch.inference_mode():
        return ce(**b).logits[:, ENT].float().cpu().numpy()

def norm_margin(s, g):
    return (s[g] - np.delete(s, g).max()) / (s.std() + 1e-9)

def load(key):
    cfg = DATASETS[key]
    ds = load_dataset(cfg["hf_name"], cache_dir=DATA_CACHE)
    q, c, y = DATASET_ADAPTERS[key](ds, cfg)
    return cfg, q, c, y

def esc(s):
    for a, b in [("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"), ("_", r"\_")]:
        s = s.replace(a, b)
    return s

rng = random.Random(SEED)
rows = []

# ================= Emotion: explicit =================
LEX = {
    "sadness": ["sad", "sadness", "unhappy", "depressed", "miserable", "sorrow", "grief", "heartbroken"],
    "joy": ["happy", "joy", "joyful", "delighted", "glad", "cheerful", "pleased"],
    "love": ["love", "loved", "loving", "affection", "adore", "fond"],
    "anger": ["angry", "anger", "furious", "mad", "irritated", "annoyed", "rage"],
    "fear": ["afraid", "fear", "scared", "terrified", "frightened"],
    "surprise": ["surprised", "surprise", "shocked", "amazed", "astonished", "stunned"],
}

def explicit(text, label):
    words = LEX.get(label.lower(), []) + [label.lower()]
    return any(re.search(rf"\b{re.escape(w)}(s|ed)?\b", text.lower()) for w in words)

cfg, Q, C, Y = load(EMO_KEY)
labels = C[0] if cfg["shared_candidates"] else None
cand = [i for i in range(len(Q)) if explicit(Q[i], (labels or C[i])[Y[i]])]
print(f"Emotion: {len(cand)}/{len(Q)} items contain the label word or a synonym")
rng.shuffle(cand)

hits = []
for i in cand[:POOL]:
    opts = labels or C[i]
    g = Y[i]
    s1, s2 = e5_scores(Q[i], opts), ce_scores(Q[i], opts, EMO_TEMPLATE)
    if s1.argmax() == g and s2.argmax() == g:
        hits.append((i, s1, s2))
print(f"  {len(hits)} of {min(POOL, len(cand))} checked items are correct for both scorers")

for k, (i, s1, s2) in enumerate(hits[:5]):
    opts = labels or C[i]
    print(f"\n[Emotion cand {k}] item {i}: {Q[i]!r}\n  label: {opts[Y[i]]}")
    print("  e5  :", {o: round(float(v), 3) for o, v in zip(opts, s1)})
    print("  deb :", {o: round(float(v), 2) for o, v in zip(opts, s2)})
if hits:
    i = hits[0][0]
    opts = labels or C[i]
    rows.append(("Emotion (explicit)", rf"``{esc(Q[i])}''", esc(opts[Y[i]])))

# ================= CSQA: easy association =================
cfg, Q, C, Y = load(CSQA_KEY)
cand = [i for i in range(len(Q)) if len(Q[i]) <= MAX_Q_CHARS]
rng.shuffle(cand)

hits = []
for i in cand[:POOL]:
    g = Y[i]
    s1, s2 = e5_scores(Q[i], C[i]), ce_scores(Q[i], C[i], CSQA_TEMPLATE)
    if (s1.argmax() == g and s2.argmax() == g
            and norm_margin(s1, g) >= MARGIN_MIN and norm_margin(s2, g) >= MARGIN_MIN):
        hits.append((i, s1, s2))
print(f"\nCSQA: {len(hits)} of {min(POOL, len(cand))} short items are easy for both scorers")

for k, (i, s1, s2) in enumerate(hits[:5]):
    print(f"\n[CSQA cand {k}] item {i}: {Q[i]!r}")
    for j, o in enumerate(C[i]):
        print(f"  {'*' if j == Y[i] else ' '} {o:25s} e5={s1[j]:.3f}  deb={s2[j]:+.2f}")
if hits:
    i = hits[0][0]
    shown = ", ".join(rf"\textbf{{{esc(o)}}}" if j == Y[i] else esc(o) for j, o in enumerate(C[i]))
    rows.append(("CSQA (easy)", rf"``{esc(Q[i])}'' Options: {shown}", esc(C[i][Y[i]])))

# ---------- LaTeX rows ----------
tex = "\n".join(rf"{n} & {t} & {l} \\" for n, t, l in rows)
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(tex)
print("\n--- LaTeX rows (paste into the examples table) ---\n" + tex)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3012.89it/s]
/home/tichar/Documents/ee798/project/.venv/lib/python3.12/site-packages/torch/jit/_script.py:1491: FutureWarning: `torch.jit.script` is deprecated. Please switch to `torch.compile` or `torch.export`.
  warnings.warn(
Loading weights: 100%|██████████| 202/202 [00:00<00:00, 3651.83it/s]

Emotion: 197/2000 items contain the label word or a synonym
  153 of 197 checked items are correct for both scorers

[Emotion cand 0] item 957: 'i wonder how it feels to be loved by someone you love'
  label: love
  e5  : {'sadness': 0.811, 'joy': 0.795, 'love': 0.865, 'anger': 0.798, 'fear': 0.799, 'surprise': 0.764}
  deb : {'sadness': -2.1, 'joy': -2.77, 'love': 2.11, 'anger': -4.75, 'fear': -4.86, 'surprise': -1.82}

[Emotion cand 1] item 1650: 'i didint feel any love and caring now'
  label: love
  e5  : {'sadness': 0.751, 'joy': 0.766, 'love': 0.822, 'anger': 0.749, 'fear': 0.747, 'surprise': 0.744}
  deb : {'sadness': -2.21, 'joy': -4.29, 'love': 2.62, 'anger': -4.46, 'fear': -4.86, 'surprise': -1.3}

[Emotion cand 2] item 626: 'i remember feeling so frightened that i could feel emotions at that high a level'
  label: fear
  e5  : {'sadness': 0.787, 'joy': 0.739, 'love': 0.744, 'anger': 0.802, 'fear': 0.824, 'surprise': 0.743}
  deb : {'sadness': -4.75, 'joy': -4.95, 'love': -4.96, 'anger': -4.79, 'fear': 4.35, 'surprise': -4.36}

[Emotion cand 3] item 1167: 'i feel a kind of dull grief over it'
  label: sadness
  e5  : {'sadness': 0.851, 'joy': 0.798, 'love': 0.769, 'anger': 0.822, 'fear': 0.788, 'surprise': 0.784}
  deb : {'sadness': 4.07, 'joy': -4.88, 'love': -4.03, 'anger': -4.83, 'fear': -4.96, 'surprise': -4.18}

[Emotion cand 4] item 1775: 'i type these words i feel like i shouldn t be surprised'
  label: surprise
  e5  : {'sadness': 0.794, 'joy': 0.77, 'love': 0.786, 'anger': 0.794, 'fear': 0.794, 'surprise': 0.82}
  deb : {'sadness': -4.51, 'joy': -2.98, 'love': -4.26, 'anger': -4.6, 'fear': -4.45, 'surprise': 1.44}

CSQA: 30 of 300 short items are easy for both scorers

[CSQA cand 0] item 1180: 'Farm land makes use of what?'
    countryside               e5=0.831  deb=-1.60
    michigan                  e5=0.764  deb=-3.74
    north dakota              e5=0.756  deb=-3.69
  * farming areas             e5=0.890  deb=+0.80
    illinois                  e5=0.762  deb=-3.59

[CSQA cand 1] item 1088: 'Why does having a disability sometimes making academic tasks hard for a person?'
  * mentally challenged       e5=0.839  deb=-1.45
    have choice               e5=0.773  deb=-2.39
    lots of space             e5=0.761  deb=-4.14
    hungry                    e5=0.775  deb=-3.91
    acknowledgment            e5=0.758  deb=-2.57

[CSQA cand 2] item 85: 'The man had a fear of illness, so he never visited friends who were a what?'
  * sick person               e5=0.810  deb=-1.45
    hospital                  e5=0.765  deb=-2.37
    elderly person            e5=0.777  deb=-2.30
    graveyard                 e5=0.754  deb=-3.24
    doctor's office           e5=0.751  deb=-2.08

[CSQA cand 3] item 1176: 'She had an interest in the man, what did she want to do with him?'
    see particular program    e5=0.735  deb=-3.82
    see exhibits              e5=0.718  deb=-3.06
    see people play game      e5=0.726  deb=-2.74
  * have conversation         e5=0.764  deb=-2.28
    watch film                e5=0.728  deb=-3.40

[CSQA cand 4] item 25: 'When wildlife reproduce we often refer to what comes out as what?'
    raise children            e5=0.768  deb=-2.76
    have children             e5=0.777  deb=-2.18
    photo copy                e5=0.749  deb=-2.43
  * offspring                 e5=0.836  deb=-1.76
    accidently got pregnant somehow e5=0.789  deb=-2.82

--- LaTeX rows (paste into the examples table) ---
Emotion (explicit) & ``i wonder how it feels to be loved by someone you love'' & love \\
CSQA (easy) & ``Farm land makes use of what?'' Options: countryside, michigan, north dakota, \textbf{farming areas}, illinois & farming areas \\